// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webmvc.Context;

namespace webmvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211020085640_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("webmvc.Models.CustomerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CustomerEntity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "C1",
                            CreateDate = new DateTime(2021, 10, 20, 15, 56, 40, 111, DateTimeKind.Local).AddTicks(5860),
                            Email = "test1@gmail.com",
                            LastUpdateDate = new DateTime(2021, 10, 20, 15, 56, 40, 115, DateTimeKind.Local).AddTicks(7839),
                            NameEN = "Test1",
                            NameTH = "ทดสอบ1",
                            Phone = "9999999999"
                        },
                        new
                        {
                            ID = 2,
                            Code = "C2",
                            CreateDate = new DateTime(2021, 10, 20, 15, 56, 40, 115, DateTimeKind.Local).AddTicks(8338),
                            Email = "test2@gmail.com",
                            LastUpdateDate = new DateTime(2021, 10, 20, 15, 56, 40, 115, DateTimeKind.Local).AddTicks(8344),
                            NameEN = "Test2",
                            NameTH = "ทดสอบ2",
                            Phone = "9999999999"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
